Repository tari-project/tari-launchpad, pull requests merged in 2022-11, with the labels that each got.

#189 feat: add cli tool
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  cli/src/dashboard.rs
  cli/src/main.rs
  libs/protocol/src/config.rs
  libs/protocol/src/launchpad.rs
  libs/protocol/src/lib.rs
  libs/protocol/src/session.rs
  libs/sdm-launchpad/src/api.rs
  libs/sdm-launchpad/src/bus.rs
  libs/sdm-launchpad/src/resources/images/l2_base_node.rs
  libs/sdm-launchpad/src/wallet_grpc.rs
Labels: P-merge, P-acks_required

#194 fix: activate the bus on tauri setup
  Cargo.lock
  backend/Cargo.toml
  backend/src/main.rs
  libs/protocol/src/lib.rs
  libs/sdm-launchpad/src/lib.rs
  libs/sdm-launchpad/src/tauri.rs
Labels: P-merge

#188 fix: small edit to id display
  gui-react/src/components/CopyBox/index.tsx
  gui-react/src/components/CopyBox/styles.ts
  gui-react/src/containers/SettingsContainer/WalletSettings/WalletSettings.tsx
  gui-react/src/containers/WalletContainer/TariWallet/TariId.tsx
Labels: P-merge

#195 fix: improve cli tool
  cli/src/app.rs
  cli/src/dashboard.rs
  cli/src/main.rs
  libs/protocol/src/config.rs
  libs/protocol/src/container.rs
  libs/protocol/src/launchpad.rs
  libs/protocol/src/lib.rs
  libs/protocol/src/session.rs
  libs/protocol/src/settings.rs
  libs/sdm-launchpad/src/bus.rs
  libs/sdm-launchpad/src/resources/config.rs
  libs/sdm-launchpad/src/resources/images/l1_tor.rs
  libs/sdm-launchpad/src/resources/images/l2_base_node.rs
  libs/sdm-launchpad/src/resources/images/l2_wallet.rs
  libs/sdm-launchpad/src/resources/images/l3_miner.rs
  libs/sdm-launchpad/src/resources/images/l8_grafana.rs
  libs/sdm-launchpad/src/resources/images/l8_loki.rs
  libs/sdm-launchpad/src/resources/images/l8_promtail.rs
  libs/sdm/src/image/mod.rs
  libs/sdm/src/image/task/mod.rs
  libs/sdm/src/network/task/mod.rs
  libs/sdm/src/scope.rs
  libs/sdm/src/task.rs
  libs/sdm/src/volume/task/mod.rs
Labels: CR-too_long, P-acks_required

#192 feat: add a description for sdm
  libs/README.md
Labels: P-merge

#153 fix(ci): update GHA to include draft release and checksums
  .github/workflows/release.yml
  backend/package.json
  backend/tauri.conf.json
  libs/sdm-launchpad/Cargo.toml
Labels: CR-too_long, P-acks_required
