Repository tari-project/tari-launchpad, pull requests merged in 2023-12, with the labels that each got.

#265 feat: fix startup bugs
  cli/src/component/normal/wallet/balance.rs
  libs/protocol/src/settings.rs
  libs/sdm-assets/assets/settings.toml
  libs/sdm-launchpad/src/resources/images/l2_base_node.rs
  libs/sdm-launchpad/src/resources/images/l2_wallet.rs
Labels: P-acks_required, P-reviews_required

#266 fix: don't spam key events
  cli/src/dashboard.rs
Labels: P-acks_required

#268 ci(fix): prevent code injection
  .github/workflows/pr_title.yml
Labels: CR-insufficient_context, P-acks_required

#267 fix: simpler path for windows
  libs/sdm/src/image/task/docker.rs
Labels: P-acks_required

#270 ci(fix): modernise - dependadbot/actions/formatting
  .github/dependabot.yml
  .github/workflows/audit.yml
  .github/workflows/launchpad_v2.yml
  .github/workflows/release.yml
  .github/workflows/reusable-ci-jobs.yml
  .github/workflows/reusable-licenses.yml
  .github/workflows/reusable-tests.yml
  .license.ignore
  scripts/install_ubuntu_dependencies.sh
Labels: P-acks_required

#272 ci(fix): correct audit action
  .github/workflows/audit.yml
Labels: CR-insufficient_context

#277 feat: improvements
  README.md
  cli/src/component/normal/base_node.rs
  cli/src/component/settings/wallet.rs
Labels: P-acks_required

#278 ci(fix): improve the docker build for cross-compile
  .license.ignore
  docker_rig/tarilabs.Dockerfile
Labels: P-acks_required
