Repository tari-project/tari-launchpad, pull requests merged in 2023-08, with the labels that each got.

#223 feat: render logs
  Cargo.lock
  cli/src/component/expert/logs/mod.rs
  cli/src/component/expert/mod.rs
  cli/src/state/focus.rs
  libs/protocol/Cargo.toml
  libs/protocol/src/container.rs
  libs/sdm/src/task.rs
  libs/sim-launchpad/src/simulator.rs
Labels: CR-insufficient_context, P-acks_required

#227 ci(fix): remove unused workflow launchpad_docker.yml
  .github/workflows/launchpad_docker.yml
Labels: P-acks_required

#226 ci(fix): bump 3rd party tools
  docker_rig/monerod.Dockerfile
  docker_rig/tor.Dockerfile
  docker_rig/xmrig.Dockerfile
Labels: P-acks_required

#225 ci(fix): minotari rename
  build_images.sh
  docker_rig/tarilabs.Dockerfile
  hosted-dual.env
  tarisuite.json
Labels: P-acks_required

#229 feat: use the stagenet
  libs/protocol/src/settings.rs
  libs/sdm-assets/assets/config.toml
  libs/sdm-launchpad/src/resources/images/l2_base_node.rs
Labels: P-acks_required

#230 feat: terminate containers on exit
  cli/src/component/main_view.rs
  cli/src/component/mod.rs
  cli/src/component/termination.rs
  cli/src/dashboard.rs
  cli/src/state/focus.rs
  cli/src/state/mod.rs
  libs/protocol/src/container.rs
Labels: P-acks_required

#232 fix: ci workflows
  .github/workflows/coverage.yml
  .github/workflows/reusable-ci-jobs.yml
  .github/workflows/reusable-tests.yml
  .license.ignore
  backend/Cargo.toml
Labels: P-acks_required, P-reviews_required

#234 feat: wallet stagenet
  libs/sdm-launchpad/src/resources/images/l2_wallet.rs
Labels: P-acks_required

#235 fix: relative columns width
  cli/src/component/expert/containers/mod.rs
  cli/src/component/expert/logs/mod.rs
Labels: P-acks_required

#236 fix: wallet connection
  cli/src/component/expert/logs/mod.rs
  libs/protocol/src/session.rs
  libs/sdm-launchpad/src/resources/images/l1_tor.rs
  libs/sdm-launchpad/src/resources/images/l2_base_node.rs
  libs/sdm-launchpad/src/resources/images/l2_wallet.rs
  libs/sdm-launchpad/src/resources/images/l3_miner.rs
  libs/sdm-launchpad/src/resources/images/l5_mmproxy.rs
  libs/sdm-launchpad/src/resources/images/l5_monerod.rs
  libs/sdm-launchpad/src/resources/images/l5_xmrig.rs
  libs/sdm-launchpad/src/resources/images/l8_grafana.rs
  libs/sdm-launchpad/src/resources/images/l8_loki.rs
  libs/sdm-launchpad/src/resources/images/l8_promtail.rs
Labels: P-acks_required

#238 fix: use stagenet images for mining
  cli/src/component/normal/wallet/balance.rs
  cli/src/component/normal/wallet/mod.rs
  cli/src/dashboard.rs
  libs/protocol/src/wallet.rs
  libs/sdm-launchpad/src/resources/images/l3_miner.rs
  libs/sdm-launchpad/src/resources/images/l5_mmproxy.rs
  libs/sdm-launchpad/src/wallet_grpc.rs
  libs/sim-launchpad/src/simulator.rs
Labels: P-acks_required
