Repository tari-project/tari-launchpad, pull requests merged in 2023-11, with the labels that each got.

#242 chore: update containers
  .github/workflows/release.yml
  .github/workflows/reusable-ci-jobs.yml
  .github/workflows/reusable-tests.yml
  backend/src/docker/models.rs
  cli/src/main.rs
  libs/protocol/src/container.rs
  libs/protocol/src/settings.rs
  libs/sdm-assets/src/configurator.rs
  libs/sdm-launchpad/src/bus.rs
  libs/sdm-launchpad/src/resources/images/l2_base_node.rs
  libs/sdm-launchpad/src/resources/images/l2_wallet.rs
  libs/sdm-launchpad/src/resources/images/l3_miner.rs
  libs/sdm-launchpad/src/resources/images/l5_mmproxy.rs
  libs/sdm-launchpad/src/resources/images/mod.rs
  libs/sdm/src/image/checker.rs
  libs/sdm/src/image/mod.rs
  libs/sdm/src/image/task/docker.rs
  libs/sdm/src/image/task/events.rs
  libs/sdm/src/image/task/mod.rs
  libs/sdm/src/image/task/update.rs
  libs/sdm/src/status.rs
  libs/sdm/src/task.rs
  libs/sim-launchpad/src/simulator.rs
Labels: P-acks_required, P-reviews_required

#243 feat: compact tui
  cli/src/component/elements.rs
  cli/src/component/expert/mod.rs
  cli/src/component/mod.rs
  cli/src/component/normal/base_node/container.rs
  cli/src/component/normal/base_node/mod.rs
  cli/src/component/normal/containers/mod.rs
  cli/src/component/normal/mining/merged_mining.rs
  cli/src/component/normal/mining/mod.rs
  cli/src/component/normal/mining/tari_mining.rs
  cli/src/component/normal/mod.rs
  cli/src/component/normal/wallet/balance.rs
  cli/src/component/normal/wallet/container.rs
  cli/src/component/normal/wallet/mod.rs
  cli/src/component/normal/wallet/password.rs
  cli/src/component/normal/wallet/send_funds.rs
  cli/src/state/focus.rs
  cli/src/state/mod.rs
Labels: P-acks_required, P-reviews_required

#244 fix: get sha3 mining working
  backend/assets/config.toml
  backend/src/docker/settings.rs
  docker_rig/config.toml
  libs/protocol/src/session.rs
  libs/sdm-assets/assets/config.toml
  libs/sdm-launchpad/src/resources/config.rs
  libs/sdm-launchpad/src/resources/images/l1_tor.rs
  libs/sdm-launchpad/src/resources/images/l2_base_node.rs
  libs/sdm-launchpad/src/resources/images/l2_wallet.rs
  libs/sdm-launchpad/src/resources/images/l3_miner.rs
  libs/sdm-launchpad/src/resources/images/l5_mmproxy.rs
  libs/sdm/src/image/task/update.rs
  libs/sdm/src/task.rs
Labels: P-acks_required, P-reviews_required

#245 chore: update checkout github action
  .github/workflows/reusable-ci-jobs.yml
  .github/workflows/reusable-licenses.yml
  .github/workflows/reusable-tests.yml
Labels: P-acks_required, P-reviews_required

#247 chore: deduplicate ci tests
  .github/workflows/launchpad_v2.yml
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#246 feat: improve balance formatting
  cli/src/component/normal/wallet/balance.rs
  libs/protocol/src/lib.rs
  libs/protocol/src/tari_format.rs
  libs/protocol/src/wallet.rs
  libs/sdm-launchpad/src/wallet_grpc.rs
  libs/sdm-launchpad/tests/test_mining.rs
  libs/sim-launchpad/src/simulator.rs
Labels: P-acks_required, P-reviews_required

#249 fix: don't install node.js when doing cargo clippy
  .github/workflows/reusable-ci-jobs.yml
Labels: P-acks_required, P-reviews_required

#251 feat: merge mining
  Cargo.lock
  cli/src/component/header/mode.rs
  cli/src/component/main_view.rs
  cli/src/component/normal/containers/mod.rs
  cli/src/component/settings/mining.rs
  cli/src/component/widgets/labeled_input.rs
  cli/src/dashboard.rs
  cli/src/state/mod.rs
  libs/protocol/Cargo.toml
  libs/protocol/src/container.rs
  libs/protocol/src/launchpad.rs
  libs/protocol/src/session.rs
  libs/protocol/src/settings.rs
  libs/sdm-assets/assets/settings.toml
  libs/sdm-assets/src/configurator.rs
  libs/sdm-launchpad/src/bus.rs
  libs/sdm-launchpad/src/resources/config.rs
  libs/sdm-launchpad/src/resources/images/l2_wallet.rs
  libs/sdm-launchpad/src/resources/images/l5_mmproxy.rs
  libs/sdm-launchpad/src/resources/images/l5_monerod.rs
  libs/sdm-launchpad/src/resources/images/l5_xmrig.rs
  libs/sdm-launchpad/src/resources/images/mod.rs
  libs/sdm/src/task.rs
  libs/sim-launchpad/src/simulator.rs
Labels: P-acks_required, P-reviews_required

#248 feat: select minotari symbol
  libs/protocol/src/tari_format.rs
Labels: P-acks_required, P-reviews_required

#253 chore: spring cleaning
  Cargo.lock
  backend/src/api/base_node_api.rs
  backend/src/api/mod.rs
  backend/src/api/wallet_api.rs
  backend/src/commands/cleanup.rs
  backend/src/commands/create_workspace.rs
  backend/src/commands/events.rs
  backend/src/commands/health_check.rs
  backend/src/commands/host.rs
  backend/src/commands/launch_docker.rs
  backend/src/commands/mod.rs
  backend/src/commands/pull_images.rs
  backend/src/commands/service.rs
  backend/src/commands/shutdown.rs
  backend/src/commands/state.rs
  backend/src/docker/cleanup.rs
  backend/src/docker/container.rs
  backend/src/docker/error.rs
  backend/src/docker/filesystem.rs
  backend/src/docker/helpers.rs
  backend/src/docker/mod.rs
  backend/src/docker/models.rs
  backend/src/docker/mounts.rs
  backend/src/docker/settings.rs
  backend/src/docker/workspace.rs
  backend/src/docker/wrapper.rs
  backend/src/main.rs
  backend/src/rest/mod.rs
  backend/src/rest/quay_io.rs
  libs/protocol/Cargo.toml
  libs/sdm-launchpad/Cargo.toml
  libs/sdm/Cargo.toml
  libs/sdm/src/utils.rs
  libs/tact/Cargo.toml
Labels: P-acks_required, P-reviews_required

#254 feat: randomise tor control password
  libs/sdm-launchpad/src/bus.rs
  libs/sdm-launchpad/src/resources/config.rs
  libs/sdm-launchpad/src/resources/images/l2_base_node.rs
  libs/sdm-launchpad/src/resources/images/l2_wallet.rs
  libs/sdm-launchpad/src/resources/images/l3_miner.rs
  libs/sdm-launchpad/src/resources/images/l5_mmproxy.rs
Labels: P-acks_required, P-reviews_required

#250 ci(fix): bump 3rd party releases
  docker_rig/monerod.Dockerfile
  docker_rig/tarilabs.Dockerfile
  docker_rig/tor.Dockerfile
  docker_rig/xmrig.Dockerfile
Labels: P-acks_required

#255 chore: remove unused onboarding scene
  cli/src/component/header/mode.rs
  cli/src/component/main_view.rs
  cli/src/component/mod.rs
  cli/src/component/onboarding/message.rs
  cli/src/component/onboarding/mod.rs
  cli/src/dashboard.rs
  cli/src/lib.rs
  cli/src/onboarding.rs
  cli/src/state/bus.rs
  cli/src/state/mod.rs
  cli/src/supervisor.rs
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#256 chore: remove simulator code
  Cargo.lock
  Cargo.toml
  cli/Cargo.toml
  libs/sim-launchpad/Cargo.toml
  libs/sim-launchpad/src/bus.rs
  libs/sim-launchpad/src/lib.rs
  libs/sim-launchpad/src/simulator.rs
Labels: P-acks_required, P-reviews_required

#257 docs: add sdm readme
  libs/sdm/README.md
Labels: CR-insufficient_context, P-acks_required, P-reviews_required

#258 feat: simplify ui
  Cargo.lock
  cli/src/component/elements.rs
  cli/src/component/mod.rs
  cli/src/component/motion.rs
  cli/src/component/normal/base_node.rs
  cli/src/component/normal/base_node/container.rs
  cli/src/component/normal/base_node/mod.rs
  cli/src/component/normal/hint.rs
  cli/src/component/normal/mining/merged_mining.rs
  cli/src/component/normal/mining/mod.rs
  cli/src/component/normal/mod.rs
  cli/src/component/normal/wallet/container.rs
  cli/src/component/normal/wallet/password.rs
  cli/src/component/widgets/mod.rs
  cli/src/component/widgets/status_line.rs
  cli/src/state/onboarding.rs
  libs/protocol/Cargo.toml
  libs/protocol/src/launchpad.rs
  libs/protocol/src/lib.rs
  libs/protocol/src/node.rs
  libs/protocol/src/wallet.rs
  libs/sdm-launchpad/Cargo.toml
  libs/sdm-launchpad/src/bus.rs
  libs/sdm-launchpad/src/lib.rs
  libs/sdm-launchpad/src/node_grpc.rs
  libs/sdm-launchpad/src/resources/images/l2_base_node.rs
  libs/sdm-launchpad/src/resources/images/l2_wallet.rs
  libs/sdm/src/image/checker.rs
Labels: P-acks_required, P-reviews_required

#259 feat: report session mining stats
  Cargo.lock
  cli/src/component/elements.rs
  cli/src/component/normal/base_node.rs
  cli/src/component/normal/mining/amount.rs
  cli/src/component/normal/mining/helpers.rs
  cli/src/component/normal/mining/merged_mining.rs
  cli/src/component/normal/mining/mining_panel.rs
  cli/src/component/normal/mining/mod.rs
  cli/src/component/normal/mining/session_stats.rs
  cli/src/component/normal/mining/tari_mining.rs
  cli/src/component/normal/mod.rs
  cli/src/component/normal/wallet/container.rs
  cli/src/state/focus.rs
  cli/src/state/mod.rs
  libs/protocol/Cargo.toml
  libs/protocol/src/session.rs
  libs/protocol/src/wallet.rs
  libs/sdm-launchpad/src/resources/images/l3_miner.rs
  libs/sdm-launchpad/tests/test_mining.rs
  libs/sdm/src/image/task/events.rs
Labels: P-acks_required, P-reviews_required

#261 feat: report container download status
  cli/src/component/normal/containers/mod.rs
  libs/protocol/src/container.rs
  libs/sdm-assets/assets/config.toml
  libs/sdm-launchpad/src/bus.rs
Labels: P-acks_required, P-reviews_required

#262 fix: startup issues
  libs/sdm-assets/assets/config.toml
  libs/sdm-launchpad/src/resources/images/l2_base_node.rs
Labels: P-acks_required, P-reviews_required

#264 feat: help note
  cli/src/component/normal/wallet/balance.rs
Labels: P-acks_required, P-reviews_required
