Repository tari-project/tari-launchpad, pull requests merged in 2024-02, with the labels that each got.

#296 chore(ci): add apple arm64 build using macos-14 runner
  .github/workflows/build_cli.json
Labels: P-acks_required

#295 feat: wallet addresses on main screen
  cli/src/component/normal/mining/mining_panel.rs
  cli/src/component/normal/mod.rs
  cli/src/state/focus.rs
  libs/sdm-assets/assets/settings.toml
  libs/sdm-launchpad/src/resources/images/l5_mmproxy.rs
Labels: P-acks_required

#298 feat: settings persistence
  cli/src/component/main_view.rs
  cli/src/component/normal/mining/mining_panel.rs
  cli/src/component/normal/mod.rs
  cli/src/component/settings/mining.rs
  cli/src/component/widgets/labeled_input.rs
  libs/protocol/src/settings.rs
  libs/sdm-assets/assets/config.toml
  libs/sdm-assets/assets/settings.toml
  libs/sdm-assets/src/configurator.rs
  libs/sdm-launchpad/src/bus.rs
Labels: P-merge

#299 chore: version bump to 1.4.0
  Cargo.lock
  backend/Cargo.toml
  cli/Cargo.toml
Labels: CR-insufficient_context, P-acks_required

#301 refactor: expert mode into logs
  cli/src/component/expert/mod.rs
  cli/src/component/header/mode.rs
  cli/src/component/main_view.rs
  cli/src/component/settings/logs.rs
  cli/src/component/settings/mod.rs
  cli/src/component/settings/security.rs
Labels: P-acks_required

#300 fix: commit missing monero settings
  libs/sdm-assets/assets/settings.toml
Labels: P-acks_required

#303 feat: show warning if wallets arent set
  cli/src/component/normal/mining/mining_panel.rs
  cli/src/component/widgets/labeled_input.rs
  cli/src/component/widgets/mod.rs
Labels: P-acks_required

#304 chore: version bump to 1.5.0
  Cargo.lock
  backend/Cargo.toml
  cli/Cargo.toml
Labels: P-acks_required

#305 feat: provide docker url
  cli/src/dashboard.rs
Labels: P-merge

#307 feat: enable docker detect for wsl2
  cli/src/component/widgets/docker_detect.rs
  cli/src/dashboard.rs
Labels: P-acks_required

#308 feat: improve screen real estate usage
  cli/src/component/expert/logs/mod.rs
  cli/src/component/widgets/labeled_input.rs
Labels: P-acks_required

#309 feat: add commands list help pane
  cli/src/component/normal/legend_widget.rs
  cli/src/component/normal/mod.rs
Labels: P-acks_required

#310 fix: graceful no docker exit
  cli/src/dashboard.rs
Labels: P-acks_required

#312 feat: add a valid monero mining address
  libs/sdm-assets/assets/settings.toml
Labels: P-acks_required

#311 feat: interpret all docker states with shutdown
  cli/src/component/main_view.rs
  cli/src/dashboard.rs
  libs/sdm/src/image/task/docker.rs
  libs/sdm/src/image/task/mod.rs
  libs/sdm/src/image/task/update.rs
Labels: P-acks_required

#315 chore: version bump to v1.6.0
  Cargo.lock
  backend/Cargo.toml
  cli/Cargo.toml
Labels: P-acks_required

#317 fix: header sync and lingering volumes
  libs/protocol/src/container.rs
  libs/sdm-launchpad/src/resources/images/l2_base_node.rs
  libs/sdm-launchpad/src/resources/images/sync_progress.rs
  libs/sdm/src/image/task/docker.rs
Labels: P-merge

#319 feat: add mining threads user control
  backend/Cargo.toml
  backend/assets/config.toml
  backend/assets/log4rs.yml
  backend/tauri.conf.json
  cli/src/component/mod.rs
  cli/src/component/settings/mining.rs
  cli/src/component/widgets/labeled_input.rs
  cli/src/state/mod.rs
  docker_rig/config.toml
  docker_rig/docker-compose.yml
  docker_rig/xmrig.Dockerfile
  gui-react/package.json
  libs/protocol/src/launchpad.rs
  libs/protocol/src/lib.rs
  libs/protocol/src/settings.rs
  libs/sdm-assets/assets/config.toml
  libs/sdm-assets/assets/log4rs.yml
  libs/sdm-assets/assets/settings.toml
  libs/sdm-assets/src/configurator.rs
  libs/sdm-launchpad/src/bus.rs
  libs/sdm-launchpad/src/resources/images/l1_tor.rs
  libs/sdm-launchpad/src/resources/images/l3_miner.rs
  libs/sdm-launchpad/src/resources/images/l5_xmrig.rs
  ui/backend/tauri.conf.json
Labels: P-acks_required
