Repository tari-project/tari-launchpad, pull requests merged in 2024-01, with the labels that each got.

#281 chore(ci): add ci for tari-lp-cli
  .github/workflows/build_cli.json
  .github/workflows/build_cli.yml
  scripts/cli/install_ubuntu_dependencies-arm64.sh
  scripts/cli/install_ubuntu_dependencies.sh
Labels: P-acks_required

#284 chore(fix): ci - docker builds - hash_domains
  docker_rig/tarilabs.Dockerfile
Labels: P-acks_required

#285 chore(fix): ci - add checksum and s3 upload
  .github/workflows/build_cli.yml
Labels: P-acks_required

#287 chore(fix): ci - add version and network from settings file
  .github/workflows/build_cli.yml
Labels: P-acks_required

#289 chore(fix): ci - add osx codesign and include all assets for uploading
  .github/workflows/build_cli.yml
Labels: P-acks_required

#290 chore(fix): ci - fix typo for osx codesign
  .github/workflows/build_cli.yml
Labels: CR-insufficient_context

#291 chore: version bump to 1.3.0
  Cargo.lock
  backend/Cargo.toml
  cli/Cargo.toml
Labels: CR-insufficient_context, P-acks_required
